#!/usr/bin/env python3
"""What a checkpoint contains per family, and what it therefore does NOT let you do.

Written 2026-09-07 after this fact -- that no baseline persists its replay buffer, so resuming an
off-policy cell from a stamp restarts it against an empty buffer -- was found to exist only as
prose: a `replay_semantics` sentence inside one family's descriptor, and a hand-typed table in a
runbook. A hand-typed table drifts. The first version of that table already had: it stated the
seven-point curve density, which is true only for `rlvigen` (the one family with a
`preserve_snapshots` cadence), as though it applied to all seven.

So this script derives the table instead. The cadences come from `families.json`; the buffer claims
are checked against the actual source of each save site, so a clone edit that started persisting a
buffer would fail the check rather than silently invalidate the runbook.

    python scripts/audit_checkpoint_semantics.py            # print the table
    python scripts/audit_checkpoint_semantics.py --check     # verify the runbook's block matches
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
FAMILIES = ROOT / "datasphere" / "native" / "families.json"
RUNBOOK = ROOT / "notes" / "RUNNING-ON-PRODUCTION-HOST.md"
BEGIN = "<!-- BEGIN checkpoint-semantics (generated by scripts/audit_checkpoint_semantics.py) -->"
END = "<!-- END checkpoint-semantics -->"

# Per family: the baselines it covers, what the save site writes, and the source evidence that the
# replay buffer is not part of it. `evidence` is (path, regex) -- the regex MUST still match, or the
# claim in the runbook is no longer supported by the code.
FAMILIES_META = {
    "rlvigen": {
        "contents": "agent (networks + optimizers), timer, _global_step, _global_episode",
        "buffer": "on disk during the run, never in the checkpoint and never retained",
        "evidence": [
            ("RL-ViGen-upstream/train.py",
             r"keys_to_save\s*=\s*\['agent',\s*'timer',\s*'_global_step',\s*'_global_episode'\]"),
            ("RL-ViGen-upstream/replay_buffer.py", r"self\._save_snapshot\s*=\s*False"),
        ],
    },
    "dmc_gb": {
        "contents": "networks + optimizers",
        "buffer": "in memory only, never written",
        "evidence": [("runnable/dmc_gb/src/utils.py", r"def prefill_memory\(obses, capacity, obs_shape\)")],
    },
    "alda": {
        "contents": "networks + optimizers (sac_*_step_*.pt)",
        "buffer": "in memory only, never written",
        "evidence": [],
    },
    "idaac": {
        "contents": "[actor_critic, envs.ob_rms]",
        "buffer": "none -- on-policy",
        "evidence": [("runnable/idaac/train.py", r"_payload\s*=\s*\[actor_critic,\s*getattr\(envs,\s*'ob_rms',\s*None\)\]")],
    },
    "ppg": {
        "contents": "model<N>.jd via LogSaveHelper",
        "buffer": "none -- on-policy",
        "evidence": [],
    },
    "ctrl": {
        "contents": "flax to_bytes(train_state), optax optimizer state included",
        "buffer": "none -- on-policy",
        "evidence": [("runnable/ctrl/train_ppo.py", r"_flax_to_bytes\(train_state\)")],
    },
    "ibac_sni": {
        "contents": "model.pt",
        "buffer": "none -- on-policy",
        "evidence": [],
    },
}
OFF_POLICY = {"rlvigen", "dmc_gb", "alda"}


def check_evidence() -> list[str]:
    """Every claim above must still be visible in the source it cites."""
    failures = []
    for family, meta in FAMILIES_META.items():
        for relative, pattern in meta["evidence"]:
            path = ROOT / relative
            if not path.exists():
                failures.append(f"{family}: {relative} is missing; the claim it supports is unverified")
                continue
            if not re.search(pattern, path.read_text(errors="replace")):
                failures.append(f"{family}: {relative} no longer matches /{pattern}/ -- "
                                "the checkpoint contents claim may be stale")
    return failures


def rows(profile: str | None = "v100") -> list[dict]:
    """Cadences as the PRODUCTION profile resolves them, not as the base descriptor states them.

    [Claude 2026-09-07] The first version of this script read the base descriptor and reported
    `rlvigen` as a 7-point curve. That is the DataSphere value: `rlvigen`'s v100 profile overrides
    `preserve_snapshots` to 50000 because the container disk limit that motivated 100000 does not
    exist on the 113 GiB production host. On the profile the fleet actually runs, every family
    keeps twelve stamps plus the endpoint -- which `production_gates.gate_checkpoint_cadence_
    matches_fleet` independently pins. A table generated from the wrong profile is exactly the
    drift this script was written to stop, so it defaults to the profile production uses.
    """
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "_native_family_for_audit", ROOT / "datasphere" / "native" / "family.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    out = []
    for family, meta in FAMILIES_META.items():
        resolved = module.resolved_descriptor(family, profile=profile)
        production = resolved.get("production") or {}
        # Derived, not typed: a hand-written list here invented a "pieg" baseline that exists
        # nowhere in this project -- the third hand-copied error in this one table.
        baselines = ", ".join(resolved.get("baselines") or [family])
        save_every = production.get("save_every")
        preserve = production.get("preserve_snapshots")
        stamps = (600_000 // save_every) if save_every else 0
        kept = (600_000 // preserve) if preserve else stamps
        out.append({
            "family": family,
            "baselines": baselines,
            "contents": meta["contents"],
            "buffer": meta["buffer"],
            "resume": "NOT a full restart -- empty buffer" if family in OFF_POLICY
                      else "effectively complete",
            "save_every": save_every,
            "preserve": preserve,
            "curve_points": kept + 1,   # retained stamps plus the endpoint
        })
    return out


def table() -> str:
    lines = [
        "| family | baselines | checkpoint contains | replay buffer | resume from a stamp |",
        "|---|---|---|---|---|",
    ]
    for row in rows():
        lines.append(f"| `{row['family']}` | {row['baselines']} | {row['contents']} | "
                     f"{row['buffer']} | **{row['resume']}** |")
    lines.append("")
    lines.append("| family | saves every | retains every | curve points at 600k |")
    lines.append("|---|---|---|---|")
    for row in rows():
        preserve = f"{row['preserve']}" if row["preserve"] else "all stamps"
        lines.append(f"| `{row['family']}` | {row['save_every']} | {preserve} | {row['curve_points']} |")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the runbook's generated block matches, and exit non-zero if not")
    args = parser.parse_args()

    failures = check_evidence()
    for failure in failures:
        print(f"EVIDENCE STALE: {failure}", file=sys.stderr)

    generated = table()
    if not args.check:
        print(generated)
        return 1 if failures else 0

    text = RUNBOOK.read_text()
    if BEGIN not in text or END not in text:
        print(f"{RUNBOOK.name} has no generated checkpoint-semantics block", file=sys.stderr)
        return 1
    current = text.split(BEGIN, 1)[1].split(END, 1)[0].strip()
    if current != generated.strip():
        print(f"{RUNBOOK.name}'s checkpoint-semantics block is out of date; regenerate it",
              file=sys.stderr)
        return 1
    print(f"checkpoint semantics: {len(rows())} families, evidence intact, runbook in sync")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
