#!/usr/bin/env python3
"""What every script in this repo is for, generated from the scripts themselves.

    python scripts/script_inventory.py            # print the table
    python scripts/script_inventory.py --write    # write it into the operator guide
    python scripts/script_inventory.py --check    # fail if the guide's block is stale

## Why generated and not written

There are 130 executable entry points across `scripts/`, `datasphere/native/` and
`datasphere/native/host-scripts/`. An operator asking "is there already a tool for this?" currently
has no way to find out except `ls`, and a hand-maintained table of 130 rows would be wrong within a
week -- this project has watched a 725-line guide go eight days stale without anyone noticing.

So the summary comes from each file's own first docstring line (Python) or its first comment line
after the shebang (shell). A script whose purpose is unreadable from its own head appears as
`(no summary)`, which is a finding about that script rather than a gap in this table.

## What this is NOT

Not a claim that every script is current, correct, or safe to run. Several are one-shot diagnostics
kept for provenance, and `host-scripts/README.md` classifies those separately. This answers "what
exists and roughly what for", which is the question that currently has no answer at all.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
GUIDE = ROOT / "notes" / "RUNNING-ON-PRODUCTION-HOST.md"
BEGIN = "<!-- BEGIN script-inventory (generated by scripts/script_inventory.py) -->"
END = "<!-- END script-inventory -->"

GROUPS = (
    ("scripts", "scripts", "*.py"),
    ("datasphere/native", "datasphere/native", "*.py"),
    ("datasphere/native", "datasphere/native", "*.sh"),
    ("datasphere/native/host-scripts", "datasphere/native/host-scripts", "*.sh"),
)


def summary_of(path: pathlib.Path) -> str:
    """First docstring line for Python; first real comment line for shell."""
    try:
        text = path.read_text(errors="replace")
    except Exception:
        return "(unreadable)"
    if path.suffix == ".py":
        m = re.search(r'^\s*(?:"""|\'\'\')(.+?)$', text, re.M)
        if m:
            return m.group(1).strip().rstrip('"\'').strip()
        return "(no summary)"
    for line in text.split("\n"):
        s = line.strip()
        if s.startswith("#!") or not s:
            continue
        if s.startswith("#"):
            body = s.lstrip("#").strip()
            if body:
                return body
        else:
            break
    return "(no summary)"


def build() -> str:
    out = [BEGIN, ""]
    total = 0
    for label, rel, pattern in GROUPS:
        d = ROOT / rel
        files = sorted(d.glob(pattern)) if d.is_dir() else []
        files = [f for f in files if f.name != "__init__.py"]
        if not files:
            continue
        out.append(f"**`{label}/{pattern}`** — {len(files)} file(s)")
        out.append("")
        out.append("| script | what it is for |")
        out.append("|---|---|")
        for f in files:
            s = summary_of(f).replace("|", "\\|")
            out.append(f"| `{f.name}` | {s[:150]} |")
        out.append("")
        total += len(files)
    out.append(f"*{total} entry points. Generated; do not edit by hand.*")
    out.append("")
    out.append(END)
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    block = build()

    if not (args.write or args.check):
        print(block)
        return 0

    text = GUIDE.read_text()
    if BEGIN not in text or END not in text:
        print(f"{GUIDE} has no inventory markers. Add:\n{BEGIN}\n{END}")
        return 2
    start, end = text.index(BEGIN), text.index(END) + len(END)
    current = text[start:end]

    if args.check:
        if current.strip() != block.strip():
            print("The script inventory in the guide is STALE. Regenerate:")
            print("  python scripts/script_inventory.py --write")
            return 1
        print(f"script inventory current ({block.count(chr(10) + '| `')} entries)")
        return 0

    GUIDE.write_text(text[:start] + block + text[end:])
    print(f"wrote the inventory into {GUIDE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
